datalab_cohorts/__init__.py, tests/test_expectations.py
I've ported these over from changes I had to make to get data generation working in the ICS repo. These need corresponding tests really, and I'm not sure if what I've done with booleans is quite the right thing, but I didn't want to lose track of these changes.
=> Small fixes to data generation code

cohortextractor/mssql_utils.py, tests/test_tpp_backend.py
Using `sqlcmd` in batch mode causes errors to be printed to stdout
without any error status
Fixes #189
=> Ensure SQL errors are propagated

cohortextractor/remotejobs.py
=> Provide workaround for pasting-password issue

cohortextractor/remotejobs.py
This should be cleaned up at a later date
=> Revert to ebmbot-specific environment variable

cohortextractor/dashboards/vaccinations.py, tests/dashboards/test_vaccinations.py
This can certainly be improved in many ways, but it's better than nothing.
=> Add dummy data generation to vaccinations study def

README.md
This is not really a `fix`, but I want to test triggering a new release.
=> Tweak docs and in doing so test release-making

.github/workflows/build_and_publish.yaml, cohortextractor/mssql_utils.py, tests/test_tpp_backend.py
Replaces #228 with a cleaner commit history
=> Sql credential error logging

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
See https://ebmdatalab.slack.com/archives/C63UXGB8E/p1593514641061200 for discussion
=> Add was_ventilated as possible returning value for admitted_to_icu

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_acme_backend.py, tests/test_tpp_backend.py
=> feat: add cause of death as return value to ONS death filters

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
=> Feat: Implement patients.admitted_to_hospital

cohortextractor/remotejobs.py
Belongs with https://github.com/opensafely/job-server/commit/aa0fab14e7b651b7e5642408ca3f9cdbf92d4a95
=> Rename output_url field

cohortextractor/cohortextractor.py
This will allow us to support different versions of study definition
syntaxes within one project, and different project pipelines for
different outputs.
Closes #259
=> feat: allow selecting single study definition for cohort generation

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
See https://github.com/opensafely/cohort-extractor/issues/182#issuecomment-669152873
=> Update patients.attended_emergency_care for new backend tables

.github/workflows/build_and_publish.yaml
See https://github.com/opensafely/job-runner/issues/20 for details
=> feat: push docker images to our own docker registry

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
=> fix: work around the fact dupes can appear in ONS data

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
=> feat: Add is_prison as allowed return value for household_status_as_of

cohortextractor/tpp_backend.py
Our server contains both the full dataset and a smaller sample of the
data for rapid testing. It's not inconceivable that we'd end up running
the same extract on these at overlapping times. Previously this would
have caused a cache key collision, but now we include the name of the
database in the list of things which get hashed to create the key.
=> fix: Fix potential cache key clash in temporary tables

cohortextractor/cohortextractor.py, cohortextractor/date_expressions.py, tests/test_tpp_backend.py
=> Handle date expressions in all date arguments

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
=> feat: Support returning MixedSoftwareHousehold column

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
This provides the bare minimum of machinery required to solve #301. It's
possible that we'll want to do something more complicated later.
=> feat: Support returning MSOA of household

cohortextractor/cohortextractor.py
=> fix: Show timestamps in exception tracebacks

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
As well as having a net-negative line count this simplifies some of the internal data structures and generally (I think) gives the code a slightly clearer conceptual model.
Closes #305
=> Refactor codelist handling in TPP backend

setup.py
=> fix: include prettytables in setuptools install_requires

setup.py
=> fix: bump jobrunner in setuptools

Dockerfile, requirements.in, requirements.txt, setup.py
Fixes to support running cohortextractor on Windows or within a Docker container
=> Windows / docker support fixes

requirements.in, requirements.txt, setup.py
This contains further cross-platform (path-related) fixes
=> fix: upgrade jobrunner

requirements.in, requirements.txt, setup.py
This is required to incorporate Windows path consistency fix
=> fix: bump jobrunner

requirements.txt
This doesn't affect PyPI installations, which use setup.py, but it does
affect the Docker images.
=> fix: Update version of job-runner used in requirements.txt

cohortextractor/emis_backend.py, tests/emis_backend_setup.py, tests/helpers.py, tests/test_emis_backend.py, tests/test_tpp_backend.py
This PR contains all the changes required to get the EMIS backend to produce SQL required for https://github.com/opensafely/restoration-observatory-emis-research.
=> Update EMIS backend for SRO work

cohortextractor/presto_utils.py, docker-compose.yml, requirements.in, requirements.txt
Docs at https://github.com/ebmdatalab/datalab-team-manual/pull/9.
=> feat: Support connecting to Presto with a PKCS#12 certificate

cohortextractor/study_definition.py, tests/test_expectation_generators.py
Actually supporting these correctly during dummy data generation is a
much bigger chunk of work, but for now we just want to ignore them so it
doesn't blow up.
=> fix: Allow dynamic dates to work with dummy data

cohortextractor/cohortextractor.py
Closes #379 and depends on #395
=> fix: Stop pandas converting empty string to None

cohortextractor/emis_backend.py, cohortextractor/presto_utils.py, requirements.in, requirements.txt
This is all fairly speculative, but might help us characterise the problems
=> Retry failed queries

cohortextractor/cohortextractor.py
See also opensafely/opensafely-cli@ee86af2
=> fix: Support user-namespaced codelists

run.sh
The new version is simpler as well.
=> fix: Fix run.sh script to work with new Docker image

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
This is prompted by the need to query the High Cost Drugs data in which
drug names are (apparently) entered as free text. This leads to names
such as:
infliximab-remicade!100mg!infusion
infliximab 'remicade' (10ml vi
infliximab 'remicade' (10ml vial)
ixekizumabß
Given the presence of single quotes in these names the only way we can
use them in queries is to escape them properly.
We also take this opportunity to correctly escape wildcard characters in
strings which are going to be used in LIKE queries.
=> fix: Escape characters rather than using a safelist

cohortextractor/emis_backend.py, cohortextractor/patients.py, cohortextractor/tpp_backend.py, tests/emis_backend_setup.py, tests/test_emis_backend.py, tests/test_tpp_backend.py
=> feat: Add ignore_missing_values option for with_these_clinical_events()

cohortextractor/presto_utils.py, tests/test_presto_utils.py
Env vars are PRESTO_TLS_KEY and PRESTO_TLS_CERT
Encrypted pkcs files still supported for now, although we probably want
to drop it at some point
Tried to write a test for the pkcs stuff, but OpenSSL (which
requests_pkcs uses) didn't like the test cert I generated with
cryptography for some reason. Given we'll probably drop it, I figured it
wasn't worth it.
=> fix: add support for plain text cert/key in env var

cohortextractor/emis_backend.py
This got pushed after #478 got merged.
=> Improve comment

.pre-commit-config.yaml, cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, pytest.ini, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
This adds `patient_with_ethnicity_from_sus()` to allow:
```python
patients.with_ethnicity_from_sus(
returning="code",  # group_6 and group_16 also available
)
```
Fixes #270
=> Add Ethnicity from SUS

cohortextractor/emis_backend.py
If set, this will run ANALYZE over the temporary tables we create.
There is a hypothesis that this will speed up subsequent queries.
We cannot easily test this because it is only supported in the Hive
connector.
=> feat: Add RUN_ANALYZE environment variable

cohortextractor/emis_backend.py, tests/test_emis_backend.py
This is a good illustration of the limits of the existing approach to building SQL queries!
=> fix: Fix date arithmetic for with_vaccination_record in EMIS backend

cohortextractor/emis_backend.py, tests/test_emis_backend.py
Previously we generated synthetic sequential IDs for each extract but
this made it impossible to match patients across extracts which we
sometimes need to do. We now use just part of the original hash:
> EMIS patient IDs are 128 byte strings which significantly bloat our output
> files. However, because they are actually hex-encoded SHA-512 hashes we can
> get away with throwing away all but the first 63 bits and storing them as
> int64s (63 bits so we can safely store them as signed int64s without
> worrying about negative patient IDs, which might upset expectations
> elsewhere). 63 bits still gives us plenty of entropy as sqrt(2^63) is about
> 2 billion so well above the threshold where we'd need to worry about
> collisions with a population of a few tens of millions.
Note that this …
=> fix: Output consistent patient IDs

cohortextractor/emis_backend.py, tests/test_emis_backend.py
Sometimes a clinician will want to record that an event has happened at some
point in the past without knowing the specific date. In TPP such events are
given a date of 1900-01-01 and in EMIS they are given a date of NULL.
However, we already use NULL as a value to indicate that a patient had no
matching event at all, so we need another value to indicate "they had a
matching event but at an indeterminate time in the past". For consistency's
sake we use the same date as in TPP.
Closes #522
=> Treat NULL observations dates as 1900-01-01

cohortextractor/pandas_utils.py
=> fix: Use correct Stata date type

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
Full list of possible variant values at present is below, but this is obviously subject to change.
=> feat: Support variant data in SGSS

cohortextractor/patients.py
=> docs: Note that `between` is inclusive

cohortextractor/study_definition.py, tests/test_expectation_generators.py
This is neither a pretty nor general solution, but it does unblock using
this queries.
Closes #404
=> fix: Generate dummy data for minimum_of/maximum_of queries

DEVELOPERS.md, README.md
* Update the OpenSAFELY framework details
* Move content and merge from README.md into DEVELOPERS.md
=> docs: Tidy the docs slightly

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
=> feat: Support querying `HealthCareWorker` table

cohortextractor/patients.py, cohortextractor/study_definition.py
=> fix: amend typos `expecation`

cohortextractor/pandas_utils.py, cohortextractor/validate_dummy_data.py
No new tests added, since change in behaviour is tested by `validate_dummy_data()`.
=> fix: Ensure patient_id is an int in dummy data

.github/workflows/emis_presto_version_check.yaml, .github/workflows/emis_trino_version_check.yaml, tests/test_presto_docker_version.py
Fixes #620.
Check the Starburst version running on EMIS, daily every weekday.
=> ci: Add regular version check for Starburst

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
Fixes #581; see that issue for more context.
=> feat: Add `symptomatic` as return option for SGSS

cohortextractor/patients.py
=> fix: Tweaks RCT docs

cohortextractor/trino_utils.py
This change, combined with writing errors to stderr and exiting with the
appropriate exit code, makes it easier to use this command as part of an
automated test.
=> feat: Support supplying SQL to trino_utils command

cohortextractor/emis_backend.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_validate_dummy_data.py
=> Fix dummy data validation for date categories

cohortextractor/tpp_backend.py
I've confirmed that this fixes the issue in the specific study that hit it.
=> fix: Fix ambiguous column error in SQL

cohortextractor/patients.py
=> docs: Fix link in high cost drugs description

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
Also adds tests for date joins in `with_covid_therapeutics`
=> fix: reference the correct table in therapeutics date joins

cohortextractor/patients.py
=> fix: Fix indentation in with_covid_therapeutics docstring

cohortextractor/process_covariate_definitions.py, tests/test_study_definition.py, tests/test_tpp_backend.py
We check all the date formats in a study definition, including those in an aggregate (e.g. `minimum_of`).  This assumed that all columns in an aggregate would be simple variables, not aggregates themselves.  
Fixes #739
=> fix: check aggregate date formats recursively

docker-compose.yml
EMIS have updated their Trino version.
=> chore: Update Starburst Trino image to 364-e.4

cohortextractor/mssql_utils.py, cohortextractor/trino_utils.py, requirements.dev.in, requirements.dev.txt, requirements.prod.txt, setup.py, tests/emis_backend_setup.py, tests/helpers.py, tests/tpp_backend_setup.py
- chore: remove requests_pkcs dependencies and its children.
- chore: move sqlachemy to being a dev only dependency
- chore: remove uneeded dependencies
=> dependency cleanup

cohortextractor/cohortextractor.py, cohortextractor/emis_backend.py, cohortextractor/mssql_utils.py, cohortextractor/trino_utils.py, tests/test_emis_backend.py
Not sure why these weren't picked up locally or in CI for #766 so here we are
=> chore: apply black fixes

cohortextractor/mssql_utils.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
=> Add exponential backoff to MSSQL database retries

cohortextractor/patients.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
Note: this is based on an assumption about what the data will look like when we actually get it, but we'll need to wait for that to come through before we can verify this and merge the PR (hence marking it as draft).
=> feat: Support new SGTF field in SGSS data

cohortextractor/cohortextractor.py, cohortextractor/generate_codelist_report.py, tests/test_generate_codelist_report.py
generate_codelist_report generates a pair of CSV files reporting on
usage of codes in a given codelist.
Paired on with @lucyb.
=> feat: Add generate_codelist_report

cohortextractor/generate_codelist_report.py, tests/test_generate_codelist_report.py
Fixes opensafely-core/interactive.opensafely.org#114
=> feat: Add patient counts to codelist report

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
Fixes #848 
See [this slack thread](https://bennettoxford.slack.com/archives/C63UXGB8E/p1658240257901219)
=> Disambiguate columns in with_an_ons_cis_record

cohortextractor/date_expressions.py, tests/test_date_expressions.py, tests/test_emis_backend.py, tests/test_tpp_backend.py
=> feat: Add date expressions for first and last day of school year

.github/workflows/build_and_publish.yaml
Also update and pin all 3rd party actions
=> fix: docker version label

.github/dependabot.yml, .github/workflows/emis_trino_version_check.yaml, .github/workflows/test_runner.yaml
And configure Dependabot to check in future, as per https://github.com/opensafely-core/repo-template/commit/e3fb61adc601ae75efce1ce5b547afda02ebd683.
=> Update GitHub Actions

cohortextractor/cohortextractor.py, cohortextractor/update_vmp_mapping.py, tests/test_update_vmp_mapping.py
This command updates the VmpMapping table with the latest data from OpenCodelists, accessed via the proxy.
=> feat: Add update_vmp_mapping command

cohortextractor/codelistlib.py, tests/test_codelistlib.py
See issue raised at:
https://github.com/opensafely-core/opencodelists/pull/1551#pullrequestreview-1328073008
=> fix: Ignore blank lines in CSV codelists

cohortextractor/custom_medication_dictionary.csv, tests/test_update_custom_medication_dictionary.py
Thanks for providing the mappings, @chrisjwood16. For background, see [1]; and opensafely-core/ehrql#1270.
[1]: https://bennettoxford.slack.com/archives/C03HVM72273/p1687786350885009
=> Update the custom medication dictionary

cohortextractor/emis_backend.py, tests/test_emis_backend.py
The implementation matches the implementation in TPP
=> feat: Handle duplicate records in ons_deaths in EMIS

cohortextractor/custom_medication_dictionary.csv
add manual diamorphine mappings by @chrisjwood16 to fix problems encountered by @alschaffer
=> Update custom medication dictionary

cohortextractor/tpp_backend.py, tests/tpp_backend_setup.py
See discussion in opensafely-core/ehrql#2047 for details
Note that archive tables contain data up to March 2024.
=> fix: Use HES archive tables

cohortextractor/cohortextractor.py, cohortextractor/tpp_backend.py, run.sh, tests/test_tpp_backend.py
The changes mean that we no longer need to pass in the current mode.
Closes:
* https://github.com/opensafely-core/job-runner/issues/888
=> Change maintenance mode detection logic
