datalab_cohorts/__init__.py
Originally these methods weren't called until we actually downloaded the
data and we wanted any errors to be raised immediately on
initialisation. But now these methods are called during init, and it
makes more sense to pull as much logic out of the syntatic sugar methods
as possible.
=> Move asserts into main body of code

DEVELOPERS.md, run.py
Multiple study definition files can now be specified using a suffix like:
```
study_definition_bright_light.py
study_definition_iv_lysol.py
```
And all the corresponding output files will have the same suffix e.g.
```
input_bright_light.csv
input_iv_lysol.csv
descriptives_bright_light.html
descriptives_iv_lysol.html
```
=> Support multiple study definitions

run.py
I thought this would be a fun occasion to try it out as we're
controlling the Python version within Docker. But of course `run.py` is
run _outside_ of Docker...
=> Remove use of Python 3.8 walrus operator

datalab_cohorts/acme_backend.py, datalab_cohorts/presto_utils.py, datalab_cohorts/study_definition.py, tests/acme_backend_setup.py, tests/test_acme_backend.py, tests/tpp_backend_setup.py
Original text by @inglesp 
--------
Here's a draft PR that brings our ACME backend closer to something that can run against ACME's data lake.
I've removed all the covariate functions apart from those used in the risk factors research, and I've marked all test tables that do not match the ACME data lake.  Other test tables do now (more-or-less, see below) match the column names and types in the ACME data lake.
The following covariate functions require ACME to add data to the lake, and as far as I know, this has not happened yet:
* `registered_practice_as_of`, for STP and Region
* `address_as_of`, for IMD and rural/urban
* `admitted_to_icu`
* `with_these_codes_on_death_certificate`
* `died_from_any_cause` 
* `with_death_recorded_in_cpns`
There are some TODOs:
* In the ACME data lake, …
=> Add ACME backend

.github/workflows/build_and_publish.yaml
Fixes #168
The downside to this is that it makes testing docker images a bit fiddly but I think this is the way round that creates least confusing.
Testing a docker image can still happen by building it from the command line.
=> Only build package/image on push/merge to master

datalab_cohorts/acme_backend.py, datalab_cohorts/patients.py, tests/acme_backend_setup.py, tests/test_acme_backend.py
With a tiny bit of special-casing in `get_column_expression`, this turns out not to be that much of a change.
=> Fix SNOMED code column type

.github/workflows/build_and_publish.yaml, .github/workflows/test_runner.yaml
This would have caught the issue with importing the library inside
setup.py earlier.
There's probably a clever way we could use the output of this build step
in the publish step so we avoid a bit of duplicated code and wasted
work, but this will do for now.
=> Test that we can build PyPI package successfully

cohortextractor/presto_utils.py, run.sh, tests/acme_backend_setup.py
It turns out that Presto will tell you it has active nodes in its `system.runtime.nodes` table but still throw a "no nodes available" error if you try to execute a query which needs to touch the MSSQL instance. This PR works around that issue.
Closes #197
=> Fix flaky Presto tests

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
Normally we require that patients stay registered throughout the study
period, but in certain cases where we have data from outside primary
care we may want to include de-registered patients in a study. For such
patients we need to know the date they de-registered so we can treat
them appropriately in the analysis.
=> feat: Support returning de-registrations dates

cohortextractor/patients.py, tests/test_expectation_generators.py
We need to find some way of making sure we (or I) don't forget to test
for this.
=> fix: Support `return_expectations` for de-registrations

cohortextractor/mssql_utils.py, tests/test_mssql_utils.py, tests/test_tpp_backend.py
Previously this code used the `-o output_file` option. This caused both
query output and warnings/errors to be mixed together in a single file,
which then required hairy and error prone code to try to separate back
out.
We now just let sqlcmd write to stdout, which we redirect to a file
ourselves, leaving error output written to stderr.
Closes #239
=> fix: Refactor sqlcmd wrapper for better error handling

.env-test, cohortextractor/acme_backend.py, cohortextractor/study_definition.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
Sometimes the queries to extract study data will run successfully but
something will interrupt the download process and then the entire query
will need to be run again.
This PR adds support for writing results to a table in a temporary
database before downloading. If the download is interrupted then a
re-run of the extraction process will pick up the previously created
table and download it without having to re-run the queries.
Once the data is successfully downloaded the table is deleted.
In order to use this feature the environment variable
`TEMP_DATABASE_NAME` must be set. This will require a change to the job
runner and updated instructions for those running extracts manually.
Fixes #241
=> Support writing results to intermediate table

cohortextractor/expressions.py, tests/test_expressions.py, tests/test_study_definition.py, tests/test_tpp_backend.py
This piggybacks off SQLite to avoid having to do our own validation.
Unfortunately this means it doesn't do any type-checking as SQLite
doesn't really do types. But still, it's better than nothing.
Partially addresses #192
=> Add basic validation of SQL expressions

.github/workflows/build_and_publish.yaml
According to the documentation, `push_git_tag` was meant to do this by
applying the current tag from the tip, but for some reason it wasn't.
Doing it explicitly is more comprehensible, in any case.
=> fix: tag docker image with version

cohortextractor/date_expressions.py, cohortextractor/process_covariate_definitions.py, cohortextractor/study_definition.py, cohortextractor/tpp_backend.py, tests/test_date_expressions.py, tests/test_tpp_backend.py
This PR adds "index_date" support to study definitions. Here is a simple example of what this looks like:
```py
study = StudyDefinition(
index_date="2015-06-01",
population=patients.with_these_clinical_events(
copd_codes,
between=[
"first_day_of_year(index_date) - 2 years",
"last_day_of_year(index_date)",
],
),
age=patients.age_as_of("index_date"),
)
```
If you define an `index_date` on a study definition then everywhere that you might normally supply a date you can now supply a "date expression".
The simplest date expression is just the string `index_date`, which gets replaced by whatever the index date is set to.
It's also possible to apply various functions to the index date. The available options (hopefully self-explanatory) are:
```
first_day_of_month(index_date) …
```
=> Add "index_date" support

cohortextractor/patients.py
This triggered an error when attempting to use the non-deprecated
`date_format` argument. And the default shouldn't have been True in
any case.
Closes #261
=> fix: Remove default True value from deprecated argument

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
Usage is pretty much what you'd expect:
```py
study = StudyDefinition(
population=patients.all(),
date_of_death=patients.with_death_recorded_in_primary_care(
returning="date_of_death",
date_format="YYYY-MM-DD",
),
died_in_2019=patients.with_death_recorded_in_primary_care(
between=["2019-01-01", "2019-12-31"],
returning="binary_flag",
),
)
```
Closes #263
=> feat: Support querying date-of-death from GP record

cohortextractor/cohortextractor.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
Example:
```
cohortextractor generate_cohort --database-url XXXXX --temp-database-name OPENCoronaTempTables
```
This PR also checks that temporary database exists before running the queries and adds a bit more logging.
=> Allow passing temporary db name on command line

.github/workflows/build_and_publish.yaml
This makes it consistent with the naming of the pip-installed console
script, thereby making running commands via docker or native python
more equivalent
=> feat: rename docker image

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
When errors occur during `generate_cohort` we want to keep the output
files around for debugging purposes but we want it to be clear that they
are not complete.
This PR produces files named like `input.partial.20200901-154348.csv`
which are only renamed to `input.csv` once the download is complete and
checks are passed.
Closes #278
=> feat: Distinguish partial and complete CSV files

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
We have decided to ignore the value of the `Ventilator` column as we don't trust it. See discussion at:
https://github.com/opensafely/cohort-extractor/issues/275#issuecomment-685684964
Instead we use the counts for days of basic and advanced respiratory support (exact meaning of these tbc with ICNARC).
Returning options are now: `had_basic_respiratory_support`, `has_advanced_respiratory_support` and `had_respiratory_support` (which covers either case).
Closes #275
BREAKING CHANGE:
1. Previously non-ventilated patients were excluded entirely from ICU results
2. The `was_ventilated` returning option has been removed.
=> Include non-ventilated patients in ICU results

.github/workflows/build_and_publish.yaml, cohortextractor/cohortextractor.py, cohortextractor/patients.py, tests/test_tpp_backend.py
This fixes two issues:
* It was impossible to display the cohortextractor version number without
having a study_definition file in the right place.
* The version number was not included in Docker builds.
=> Fixes for `cohortextractor --version`

cohortextractor/cohortextractor.py
Because we were using the value of the environment variable as the
default for an argument which was part of a mutual exclusion group it
become impossible to use `--expectations-population` while DATABASE_URL
was set.
=> fix: Fix handling of DATABASE_URL env var

cohortextractor/mssql_utils.py, cohortextractor/tpp_backend.py, tests/test_emis_backend.py, tests/test_tpp_backend.py
pyODBC and cTDS have quite different ideas about transaction management:
https://github.com/mkleehammer/pyodbc/wiki/Database-Transaction-Management
https://zillow.github.io/ctds/transactions.html
I had managed not to notice the bug here because the "happy path" for using temporary tables (where the download works first time and the temporary table can be immediately deleted) wasn't previously tested.
=> Fix transaction handling

Dockerfile, cohortextractor/tpp_backend.py
This PR adds a bit more logging around temporary tables and disabled output buffering so that log output always appears immediately.
=> Improve logging

analysis/study_definition.py, cohortextractor/cohortextractor.py, cohortextractor/emis_backend.py, cohortextractor/measure.py, cohortextractor/study_definition.py, cohortextractor/tpp_backend.py, tests/test_smoketest.py, tests/test_tpp_backend.py
* **Reinitialise backend when changing index date**
This is obviously necessary but didn't get spotted before because the
tests use the dummy data generator.
* **Ignore files without dates in the names**
Previously, if there was an `input.csv` file present it would cause the
`generate_measures` command to throw an error.
* **Support not setting `group_by`**
This is equivalent to "group everything"
Fixes #299 and addresses some of the issues raised in https://github.com/opensafely/cohort-extractor/pull/269#issuecomment-696046829
=> Fixes to measure framework

cohortextractor/tpp_backend.py
This PR improves the performance of queries which use the `ignore_days_where_these_codes_occur` option. It does this by creating a temporary table with an index on it, and then using that in the subquery rather than the enormous `CodedEvent` table.
This requires some refactoring to support creating arbitrary temporary tables. The handling of codelist tables could be subsumed into this which would simplify things but we leave that refactor for another day.
Closes #302
=> Improve performance of "not on same day" queries

cohortextractor/cohortextractor.py
The applies the same fix as in #287
=> fix: Parse CLI args even if no study_definition exists

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
In certain cases where we use the `ROWNUMBER() OVER (PARTITION BY ..`
`ORDER BY .. )` pattern to select only the first matching row in a join,
we don't specify enough order conditions to uniquely determine a first
row. When this happens the result is arbitrary (which is sort of OK) and
non-deterministic (which is not OK). This patch attempts to fix the
non-determinism by adding a tie-breaker column to the end of the sort
conditions, which is usually the ID field of the table in question.
There are two cases (the EC and APCS tables) where we can't 100%
guarantee determinstic ordering because this are no fields with a unique
constraint. However in both cases there is an "ident" field which is
almost entirely unique and where the tiny handful of duplicates are
otherwise identical and so …
=> Add ORDER BY clauses to make results deterministic

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
These methods did their own codelist-to-SQL conversion meaning that they didn't handle categorised codelists correctly.
Fixes #317
=> Better codelist handling in APCS/EC methods

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
This is accessed via the slightly verbose option name:
percentage_of_members_with_ehr_data_available
This means it can be used across other EHR systems and is hopefully
self-explanatory to someone encountering it in a study definition for
the first time.
Example:
```
percent_tpp=patients.household_as_of(
"2020-02-01", returning="percentage_of_members_with_ehr_data_available"
),
```
Closes #313
=> feat: Support returning `Household.TppPercentage` column

cohortextractor/mssql_utils.py, cohortextractor/tpp_backend.py
This PR uses a different approach to downloading results to try to work around the "EOF from server" error which has been occurring more frequently. We now download results in small batches which should (we think) be less likely to trigger the error and (more importantly) can be automatically retried if they fail so the user shouldn't have to do anything special to handle these errors.
=> Use batched downloads to work around "EOF" issue

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
A patient appears twice in the ONS data with different dates of death
(offset by one day). This results in an error when running the extract.
As we need to extract this cohort urgently we're going to use the
minimum date for now, pending a full discussion of how best to handle
this kind of inconsistency.
=> fix: Quick fix for inconsistent ONS death data

.github/workflows/build_and_publish.yaml
github didn't like backticks in the comment, apparently, so have removed.
=> feat: fake release to test docker push action

cohortextractor/expressions.py, tests/test_expressions.py
We sometimes have a legitimate need to compare values to the empty
string.
=> feat: Allow empty string literals in expressions

.gitignore, cohortextractor/patients.py
Following some iteration, these should eventually make it to
our documentation, automatically.
The main point of discussion is if there's benefit to moving to a more typed API sooner rather than later. For example, enums for `date_format`, custom types for `return_expectations`, etc.
On the one hand, this will tighten up our contracts and improve the documentation.
On the other hand, tightening up our contracts will force a major rationalisation / refactor which we know is coming but maybe isn't a top priority.
Here's how it renders in `mkdocstring`:
=> Trial of google-style docstrings

setup.py
job-runner v2 has a shim file `jobrunner/job.py` which presents the same
API as the old job-runner and makes it a drop-in replacement.
=> Bump jobrunner dependency

cohortextractor/cohortextractor.py, cohortextractor/measure.py, tests/fixtures/smoketest/analysis/study_definition.py, tests/test_smoketest.py
Just supply a list or tuple of `group_by` columns e.g
```py
measures = [
Measure(
id="liver_disease_by_stp_and_sex",
numerator="has_chronic_liver_disease",
denominator="population",
group_by=["stp", "sex"],
),
]
```
Closes #355
=> feat: Support multiple columns in measure `group_by`

cohortextractor/study_definition.py
This way the `patient_id` is more representative of those in the real data, rather than a sequential list of integers. This fixes a specific issue with https://github.com/opensafely/matching, which drops the patients in one extract from another extract. Previously, the two extracts had identical `patient_id` in the dummy data, leading to all dummy patients being dropped, e.g. in [this error](https://github.com/opensafely/post-covid-thrombosis-research/runs/1524905879?check_suite_focus=true).
To consider: I can't remember if `patient_id` in the real data end up sorted, might be worth also sorting them here if so?
Also, re: the deleted comment, I'd argue that we always need the `patient_id` col in the output.
=> Randomise dummy data patient_id

cohortextractor/cohortextractor.py
=> fix: Download codelist CSVs with correct line endings on Windows

cohortextractor/date_expressions.py, tests/test_date_expressions.py
This also removes `-` as an allowed character, which we should never have supported.
=> fix: Allow digits in column names

cohortextractor/expectation_generators.py, tests/test_expectation_generators.py
=> fix: Generate correct "empty" values in dummy data

.github/workflows/build_and_publish.yaml
This should speed up builds, since it can skip building earlier layers
that haven't changed
=> Pull image before building in GH Action

cohortextractor/emis_backend.py, tests/test_emis_backend.py
There are a handful of duplicate IDs in EMIS
=> fix: only warn on duplicate rows in EMIS

cohortextractor/patients.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
This is technically a breaking change, but this argument isn't used by
any existing studies.
=> fix: Use correct coding system for APCS procedures

cohortextractor/patients.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
As discussed in:
https://github.com/opensafely/cohort-extractor/issues/403#issuecomment-755664777
This also changes the canonical `returning` option in
`registered_practice_as_of` from `msoa_code` to `msoa` for consistency
(though `msoa_code` is still supported for now to avoid breakages).
=> feat: Support getting MSOA from patient address

cohortextractor/expectation_generators.py, tests/test_expectation_generators.py
This reflects what we have in the real data. Prior to #395 this issue
was masked by the fact that the presence of Nones in the column caused
Pandas to serialize it using `'1'` and `''`.
Closes #411
=> fix: Use 1 and 0 for boolean columns

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
Specifically this means:
patients.registered_practice_as_of
patients.date_deregistered_from_all_supported_practices
Closes #413
=> Make practice registration queries work with dynamic dates

cohortextractor/__init__.py, cohortextractor/cohortextractor.py, cohortextractor/emis_backend.py, cohortextractor/log_utils.py, cohortextractor/presto_utils.py, cohortextractor/tpp_backend.py, requirements.in, requirements.txt
This PR:
* allows us to log SQL sent to the presto backend (by setting `LOG_SQL`)
* allows us to get debug logs from underlying libraries (by setting `LOG_LEVEL`)
* changes from `print()` to `logger.info()` for presenting information to users, which means that the output is now slightly noisier -- we may want to revisit this
=> Add logging

cohortextractor/expectation_generators.py, cohortextractor/expressions.py, cohortextractor/tpp_backend.py
This fixes two bugs in our handling of empty string values.
One is a slightly edge case bug where if you had a `categorised_as` expression whose default value was something other than zero or empty string, and you then attempted to use that column in another `categorised_as` or `satisfying` expression as an implicit boolean it would blow up with an error.
The other is that you'd get an error when attempting to use the empty string as a category in `return_expectations` e.g.
return_expectations = {
"rate": "universal",
"category": {"ratios": {"yes": 0.15, "": 0.85}},
}
=> Fix bugs in empty value handling

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
We were already handling inconsistent dates of death, but we now need to
handle inconsistent underlying causes as well.
=> fix: Handle another ONS death certificate inconsistency

cohortextractor/cohortextractor.py
In cases where the extraction is taking a very long time we might want
to grab intermediate results out before the job has finished and
generally we want the most recent ones.
Also, log the index_date before running the extract.
=> fix: Extract date ranges in reverse order

.github/workflows/build_and_publish.yaml
For now, we need to manually pull newly built images from `opensafely-core` and push them to `opensafely` so they can be used with the job-runner:
```
docker pull ghcr.io/opensafely-core/cohortextractor:latest
docker tag ghcr.io/opensafely-core/cohortextractor:latest ghcr.io/opensafely/cohortextractor:latest
docker push ghcr.io/opensafely/cohortextractor:latest
```
=> fix: Remove push to old Docker registry

.github/workflows/test_runner.yaml, Dockerfile, requirements.in, requirements.txt
This updates to Dockerfile to use the [base-docker][1] image, use pre-compiled Python binaries from apt rather than compiling using pyenv, and switches to Python 3.8.
Closes #419
[1]: https://github.com/opensafely-core/base-docker
=> Update Dockerfile and switch to Python 3.8

cohortextractor/cohortextractor.py, tests/fixtures/smoketest/analysis/study_definition.py
This was documented as a thing we supported but didn't actually work.
=> fix: Allow using "population" as a group_by column

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
This only occurs when using a dynamic date with this function.
=> fix: Fix ambiguous column name in `address_as_of`

cohortextractor/cohortextractor.py, tests/test_smoketest.py
PR #454 accidentally introduced indeterminacy to the column order for
measures output. #457 attempted to address this by using set comparison
for the headers in the test but this still left the row values in an
unexpected order leading to intermittent failures. This PR fixes the
root cause.
=> fix: Restore column order for measures

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
The updated docstring in `patients.py` contains most of the detail here.
It's now possible to access the "AllTests" data (as opposed to the "Earliest Specimen Date" data) by passing the flag:
`restrict_to_earliest_specimen_date = False` e.g
```py
last_positive_test_date=patients.with_test_result_in_sgss(
pathogen="SARS-CoV-2",
test_result="positive",
find_last_match_in_period=True,
restrict_to_earliest_specimen_date=False,
returning="date",
date_format="YYYY-MM-DD",
return_expectations={
"date": {"earliest" : "2020-02-01"},
"rate" : "exponential_increase"
},
)
```
S-gene target failure results can be obtained using `returning = "s_gene_target_failure"` e.g.
```py
sgtf_result=patients.with_test_result_in_sgss(
pathogen="SARS-CoV-2",
test_result="positive",
find_last_match_in_period=True, …
```
=> Support new SGSS tables and SGTF field

cohortextractor/patients.py
This gets pulled into the documentation automatically and my initial
attempt was generating some bad-looking HTML.
=> fix: Fix markdown formatting in docstring

.flake8, pyproject.toml
This ignores some more directories from our dev tooling in an attempt to speed up those tools.  While it's good to only run them on the directories we care about, I did not fix my speed issue (3k lines in one test module coupled with running all the tools on leaving insert mode makes for an unhappy time), however I think these bits of config are generally good to have?
=> chore: ignore more directories from the dev tooling

cohortextractor/codelistlib.py
We recently had a job which passed all tests but failed in production because it used a codelist which had trailing spaces on some of the category names, resulting in an empty codelist after filtering, which then produced an invalid query.
This PR strips codelist whitespace and also raises an error if a codelist filter has no matches.
=> Fix codelist issues

cohortextractor/study_definition.py
As far as I can tell, there's no reason not to use the `default_expectations` for non-date fields.
=> fix: Allow use of default_expectations for non-date fields

cohortextractor/patients.py
This fixes the `with_ethnicity_from_sus` docstring so it's correctly formatted by our docs.  I've tested these changes in the docs repo to confirm the formatting is correct:
=> Fix with_ethnicity_from_sus Docstring

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
This adds support for the following fields:
admission_method
source_of_admission
discharge_destination
patient_classification
admission_treatment_function_code
days_in_critical_care
administrative_category
duration_of_elective_wait
Each of these can be used as a `returning` option in
`patients.admitted_to_hospital()`.
Additionally, each of these can be used as filtering option by
prepending `with_` to the column name e.g.
```py
discharge_destination=patients.admitted_to_hospital(
with_source_of_admission="2A",
returning="discharge_destination",
)
```
As well as a single string you can match against a list of strings:
```py
discharge_destination=patients.admitted_to_hospital(
with_source_of_admission=["11", "99", "2A"],
returning="discharge_destination",
)
```
Closes #414
=> feat: Support additional APCS/SUS fields

cohortextractor/patients.py
APCS docstrings;
improved formatting of docstrings throughout to improve readability when displayed in documentation, particularly for `returning` options.
Notes:
- the household variable is not currently rendered properly in docs - I removed a tab but not sure if this will help
=> Update docstrings in patients.py

cohortextractor/emis_backend.py
This just duplicates behaviour already present in the TPP backend.
Closes #490
=> fix: Log number of results downloaded in EMIS backend

cohortextractor/README.md, cohortextractor/cohortextractor.py, cohortextractor/dashboards/vaccinations.py, cohortextractor/emis_backend.py, cohortextractor/expectation_generators.py, cohortextractor/mssql_utils.py, cohortextractor/pandas_utils.py, cohortextractor/study_definition.py, cohortextractor/tpp_backend.py, requirements.txt, setup.py, tests/dashboards/test_vaccinations.py, tests/test_emis_backend.py, tests/test_pandas_utils.py, tests/test_smoketest.py, tests/test_study_definition.py, tests/test_tpp_backend.py
This adds an `--output-format` argument to the `generate_cohort` command:
```
--output-format {csv,csv.gz,feather,dta,dta.gz}
Output file format: csv (default), csv.gz, feather, dta, dta.gz
```
Note that measures are still always generated in CSV. It would be possible the teach the `generate_measures` command to respect this flag as well, but it's more work and the necessity isn't as great here as measures files are so much smaller.
Note also that this while this should reduce memory consumption for analysis scripts, it will increase it for the cohortextractor as we now have to build an entire dataframe in memory rather than streaming directly to disk as we did with CSV. I have attempted to mitigate this by converting strings to categories on the fly instead of at the end, but until we …
=> Support binary output formats

cohortextractor/emis_backend.py
The workaround I introduced to allow the tests to run (because test and
production dbs are differently configured) broke production because I
temporarily forgot how Python scoping works.
Closes #511
=> fix: Fix silly UnboundLocalError

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
In the old days cohortextractor was run manually and it was important
that we didn't create files that looked like they were successful
outputs when they in fact had errors. We did this by writing outputs to
temporary filenames and then renaming them on success or, on error,
leaving them under their temporary names for debugging purposes.
Now that the job-runner infrastructure explicitly tracks exit codes we
don't have the same problem as it's impossible to accidentally use the
output of a failed job in another action. So using temporary files
brings unnecessary complexity. In fact, it's now actively harmful
because in the case that a cohort extraction fails the file produced
doesn't have the expected name and so doesn't match the output pattern
and is never copied out of the container. …
=> fix: Stop writing output to temporary filename first

cohortextractor/patients.py
* These lines must be `key: value`, otherwise they are incorrectly imported into `opensafely/documentation`:
```
WARNING -  mkdocstrings.handlers.python: cohortextractor.patients.household_as_of: Failed to get 'name: description' pair from 'set date.
'
WARNING -  mkdocstrings.handlers.python: cohortextractor.patients.household_as_of: Failed to get 'name: description' pair from 'within the population in question.'
```
=> Fix: docstring syntax in patients.py

cohortextractor/patients.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
When querying the Diagnoses field in the APCS data we use prefix
matching so that searching for the code `J12` will also return the code
`J120`, `J121` etc.
I initially thought this was a bug but there turns out to be a test for
precisely this behaviour. It also makes clinical sense given the
hierarchical nature of ICD-10 codes.
But we weren't doing this for the Primary Diagnosis field which is a
confusing inconsistency. It's particularly problematic with the APCS data
which seems to represent three characters codes by padding them with an
X to make them four character. As the resulting codes were not valid
ICD-10 codes there was no way to represent them in the codelist builder
and therefore. Using prefix matching sidesteps this problem.
This is possibly a slightly controversial approach; …
=> fix: Extend "prefix matching" to primary diagnosis field

cohortextractor/patients.py
For context, see opensafely/SRO-Measures#10. I've attempted to clarify what the default behaviour is, which is implicit in the kwargs, and also what happens when there is a tie-break.
=> Better document the with_these_clinical_events function

cohortextractor/pandas_utils.py
Stata's categorical support isn't quite up the job, unfortunately.
Closes #534
=> fix: Use strings not categoricals when saving as Stata

cohortextractor/patients.py
Where a patient does not have any matching address it will produce an
empty string as default.
=> docs: Clarify behaviour of carehome function

cohortextractor/emis_backend.py, cohortextractor/tpp_backend.py, tests/test_emis_backend.py, tests/test_tpp_backend.py
The old SQL we used was weird in that it applied the date range filter
condition to the aggregated (min/max) date using a HAVING clause, rather than
filtering with a WHILE and then aggregating. This was introduced in
5ac9039, I suspect just because this was the most straightforward change
to make at the time not because there's any special reason to do the
query this way. This PR brings the SQL in line with the patterns we use
elsewhere and makes it work with dynamic dates.
We also update the equivalent query in the EMIS backend to fix this bug, support
the additional options we've implemented in TPP and to match the behavioural
change we introduced in #284.
=> Fix ICU queries when used with dynamic dates

.github/workflows/test_runner.yaml
This caching is intended to speed up the builds to avoid repeatedly
downloading and installing the same set of packages. However it is
somewhat unreliable: we sometimes get builds failing because the
virtualenv is unusable (for unknown reasons) and when that happens there
is no way to clear the cache without modifying the PR's commits.
This change removes the caching, sacrificing a bit of speed for improved
reliability.
=> Don't cache the virtualenvs between jobs

cohortextractor/pandas_utils.py
For outputting to Stata format there were previous fixes made to the date (#538) and category (#541) formats. However the `dtype` comparisons for both appeared not to be working as intended, meaning that no columns were identified as categories or dates, and no changes were made. These tweaks should fix that.
=> fix: dtype comparisons for Stata output format

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
Currently active registrations are recorded as having an end date of
9999-12-31. This is an internal detail we shouldn't leak: we should
instead return a deregistration date of NULL for currently registered
patients. Aside from being inelegant, this date can't be represented as
a Pandas timestamp and so it causes binary exports to fail.
We already attempted to do the right thing here, but the code was buggy
and the tests inadequate.
Closes #500
=> fix: Don't leak internal 9999-21-31 deregistration date

cohortextractor/emis_backend.py, cohortextractor/patients.py, cohortextractor/tpp_backend.py
Previously this blew up due to a set/list confusion.
We also document and enforce that these functions don't take a `return_expectations` argument.
=> Fix bug with minimum_of/maximum_of queries

cohortextractor/date_expressions.py, tests/test_emis_backend.py, tests/test_tpp_backend.py
This wasn't caught previously as the tests didn't exercise this code and
no one had used it in production.
=> fix: Presto and MSSQL functions were the wrong way round

cohortextractor/cohortextractor.py, cohortextractor/measure.py, tests/test_smoketest.py
This fixes a relatively simple, though annoying to track down, bug in the measures framework when using the "population" column as both a numerator (to get per-capita values) and as a group_by column (to treat the entire population as a single group). In this case, the group_by operation overrides the sum, so that the population column ends up with a value of 1, rather than the sum of the population. There was a measure exercising this behaviour in the test fixture, but nothing was asserted about its output.
This PR correctly handles the "population" case, and raises an error for any other cases of overlap between numerator/denominator and group_by columns.
=> Fix bug with "group by population"

Dockerfile, requirements.txt
Thanks to PySpark our dependencies are now pretty big. Previously, due
to the structure of our Dockerfile every code change however minor
required all dependencies to be re-installed into a new layer which
makes the update much larger for users to pull down.
This PR seperates out the installation of our dependencies from
the installation of the code which should mean that small code changes
require only small new layers to be pulled.
=> chore: Restructure Docker build for better layering

requirements.in, requirements.txt, setup.py, tests/test_study_definition.py
Although most usage of the cohortextractor is via the Docker image we built there are still two contexts in which we want to pip install it:
1. When building the docs so we can pull the relevant docstrings and function signatures into the docs
2. Inside the python-docker image so that researchers can import their own study definitions as part of their analysis pipeline.
In neither case do we need to actually talk to a real database and thus we don't need all the heavyweight driver dependencies.
This PR makes those optional dependencies (under the name `drivers`) and restores a test to ensure we don't accidentally import any of these when loading a study definition.
=> Make driver packages an optional dependency

requirements.in, requirements.txt, setup.py
Including the direct download URL in setup.py caused it to be rejected
by PyPI:
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Invalid value for requires_dist. Error: Can't have direct dependency: "ctds @ https:// ...
=> fix: Fix packaging

cohortextractor/emis_backend.py
We have documented the limitation, and as far as I know, nobody has
ever noticed the warning.
We're doing this now, because validation breaks on non-literal date
expressions, which we need for a study.
=> fix: Remove validation that registration history date is recent

cohortextractor/pandas_utils.py, tests/test_study_definition.py
In Pandas, all null values should be given a category index of -1.
Previously we used a Python truthiness test which treated NaNs as being
non-null meaning we tried to create a new category with the value `NaN`
which blows up.
Closes #627
=> Treat NaN values as being null

cohortextractor/databricks_backend.py, run.sh
Fixes #586.
This PR adds an environment variable `DATABRICKS_DATASOURCE_DATABASE_URL` to optionally replace the previously hardcoded URL to use for the database tests. This solves the problem where the Databricks tests fail when run within `docker-compose`, e.g. via `run.sh`.
This isn't ideal, especially that a workaround for the tests is in the code, but:
* the URL is already hardcoded for the tests, as it is right now;
* the tests are already monkeypatching `DATABRICKS_DATABASE_URL` and this URL actually needs to start with `databricks` for `get_backend_for_database_url()` to not raise an exception;
* this Databricks code is still in development, not used in production and will likely change in future when there is a more definite implementation.
This PR also fixes the …
=> test: Make the Databricks tests pass inside Docker

cohortextractor/study_definition.py, tests/test_expectation_generators.py
- add `**extra_columns` column definition to min and max variables in `test_make_df_from_expectations_with_aggregate_of()`
- create columns in for aggregation but not output within `make_df_from_expectations()`:
- make temporary inner df for extra columns
- cast columns of temporary df to dtype of first column of `*columns` arg of aggregate column
- *hacky workaround to fact that date columns in temp df will be converted to string as last step of generation*
- concat temporary df with `*columns`-based columns
- pass these concatenated columns to existing aggregation steps
=> fix: #636 minimum_of fails expectations generation with **extra_columns

cohortextractor/patients.py
Fixes opensafely/documentation#359.
=> fix: Correct wording for `include_month`

cohortextractor/study_definition.py, tests/test_expectation_generators.py
Corrects inadequacies of ecbc922 
- added test scenarios to cover 3 ways in which aggregates can be used
- using variables defined elsewhere in study
- using variables only defined within aggregate
- using a mixture of these
- test integer aggregations as well as date aggregation
- derive data type of columns defined within aggregate using inner study pandas_csv_args
- convert date columns stringified at end of extra_df generation back to dates
- datetime-like datatype required for mixed aggregation and stringification at end of method
=> fix: #636 support all aggregation scenarios in expecations generation

cohortextractor/emis_backend.py, tests/test_emis_backend.py
The [documentation for MSOA](https://docs.opensafely.org/study-def-variables/#cohortextractor.patients.registered_practice_as_of) says that `"msoa"` should be used to specify it. This works in TPP, (which also supports using `"msoa_code"`), but in EMIS only `"msoa_code"` works. This has tripped people up a couple of times.
This PR should make the EMIS backend consistent with TPP: https://github.com/opensafely-core/cohort-extractor/blob/4a339e7fb67a980ee5e9719008afbf25b43c0052/cohortextractor/tpp_backend.py#L1292-L1295
=> fix: msoa EMIS backend inconsistency

cohortextractor/patients.py
Fixes #364.
This information is already in the function definition. In the
documentation, we show the default value as a separate column. This
means that we get duplication where we say "The default value is `None`"
and then show the default is `None`.
This is also brittle in that someone might modify a default, but forget
to update the docstring, or vice versa.
=> docs: Remove redundant value type from docstrings

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
* more functionality from https://github.com/opensafely-core/cohort-extractor/issues/492
* return `consultation_medium_used`
* return either first or last match
* also improve `date` return values to return first or last
=> feat: implement consultation medium return values for outpatient appointments

cohortextractor/patients.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
Patients can have multiple COVID tests and knowing how many they have had tells us something about their health seeking behaviour and propensity for testing. At present, we can only get information about 1 test at a time. 
See #563 for more Background information.
This PR changes the code in `tpp_backend.py` to get a count of all the times that a patient has appeared in one or both tables called `SGSS_AllTests_Negative` and `SGSS_AllTests_Positive`. It then sums these counts together and returns this value. 
It adds a new `returning` option which is `returning="number_of_matches_in_period"` (This is the same API as other parts of study definition that return number of matches such as `with_clinical_events()`). 
The time period can be restricted by using the `on_or_before` or `between` …
=> Support returning test counts from SGSS

cohortextractor/study_definition.py, tests/test_expectation_generators.py
As described here:
https://github.com/opensafely/documentation/discussions/406
Specifically, a KeyError was triggered when:
* `minimum_of`/`maximum_of` was used somewhere in the study with
internal (or "hidden") columns
* the `population` definition was an expression referencing other
columns.
This is due to the somewhat hacky workaround we use for generating dummy
data for these aggregation functions. (No aspersions cast on @Jongmassey
for this: before it worked in _no_ cases, now it works in some cases; so
it's definitely a strict improvement.)
I think the right fix here is to refactor things so that we generate
dummy data for all columns, hidden or visible, in one go and then we
just remove the hidden columns before writing the data out. But the
simpler fix for now is just to hardcode …
=> fix: Fix bug generating dummy data for aggregates

cohortextractor/process_covariate_definitions.py
This only affects the generation of dummy data which the tests don't
exercise.
=> fix: Use correct type for `enrolled` property

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
This fixes the issue identified here:
https://github.com/opensafely/documentation/discussions/408#discussioncomment-1334495
Previously, it was not possible to use dates as categories because:
* the system treated them as strings and wouldn't let you use them in
places where it expected a date; and
* our "reformat anything that looks like a date" hack would step in and
reformat these dates in a way that prevented them being used
elsewhere where ISO strings were expected.
Now they behave as expected so that you can use a column defined with
`categorised_as` as the input to another function which expects a date.
For example:
```py
study = StudyDefinition(
population=patients.all(),
eligible_date=patients.categorised_as(
{
"2020-04-14": "age >= 80",
"2020-06-16": "age >= 70 AND age < 80", …
```
=> fix: Allow using dates as categories

.flake8
To `starburst`.
Missed in #625, because of not searching dotfiles.
=> chore: Update `presto` directory in flake8 config

cohortextractor/study_definition.py, tests/test_expectation_generators.py
We allow `categorised_as` functions to return dates, which can then be
used as inputs to other functions. For the purposes of real data
extraction they behave like dates and should be typed as such. However
for the purposes of dummy data generation they act like categoricals
(dates get a whole load of special treatment that we don't want here).
This addresses the issue at:
https://github.com/opensafely-core/cohort-extractor/pull/656#issuecomment-927282520
=> fix: Fix dummy data generation for categorised dates

cohortextractor/trino_utils.py, requirements.txt, setup.py
This reverts the change made in #625 from using
`presto-python-client=0.7.0` to using `trino==0.306.0`. That change
passes tests but triggers 500 errors from the database in production.
Rather than revert the entire PR (which would be a revert of a revert of
a revert) we leave almost all the other changes in place and do some
import munging to access the old client under the new name. This should
buy us some time while we identify the root cause.
=> fix: Revert to using Presto client library

cohortextractor/expressions.py, tests/test_expressions.py
Following #655 we now return "comparator" categories which have
non-alphanumeric names. In order to reference these values in
expressions like
egfr =1  AND  egfr_comparator = '>'
we need to be able to include these values in string literals.
=> fix: Allow comparator characters in category names

cohortextractor/patients.py
Rename example variables accordingly
=> fix: make upper and lower bounds consistent

DEVELOPERS.md
Trying to do anything in a virtualenv on macOS is a fruitless, frustrating exercise. One reason for trying is to point `cohortextractor` to an existing study, which is much easier with a two-line change to *run.sh*. Hopefully this PR will dissuade people from the former and help them with the latter.
=> docs: Improve macOS developer docs

cohortextractor/expressions.py, tests/test_expressions.py
A researcher called `patients.categorised_as` with a logic statement that contained a 24-character string literal. The study raised a `ValueError`. It's reasonable to increase the limit from 16 characters to 64 characters. For more information, see: opensafely/documentation#504.
=> fix: Allow string literals of up to 64 characters

cohortextractor/expressions.py, tests/test_expressions.py
@elsie-h wanted to use "Yorkshire and The Humber" as a string literal in a logic expression. It is a valid NUTS 1 region name and is returned by `patients.registered_practice_as_of`. However, without allowing spaces in string literals, cohort-extractor raises a `ValueError`. For more information, see opensafely/documentation#504.
I also sneaked an extra assertion into a test 🙂.
=> Spaces in string literals

.github/workflows/emis_trino_version_check.yaml
When the separate requirements files were added in #605, this broke
because the possibility of multiple files existing wasn't accounted for.
`grep` helpfully has `--no-filename` by default when only one file is
searched. Now we're searching two requirements files, so that implicit
setting broke.
The full flags to `grep` are now included, because it's not too obvious
that `-h` means `--no-filename`.
=> ci: Fix broken Trino version check

cohortextractor/pandas_utils.py, tests/test_pandas_utils.py
TPP uses the date `9999-12-31 00:00:00` to represent a max future date,
but this is too large for `pandas.Timestamp` when we download the
results.
So, we clamp this specific date to `pandas.Timestamp.max`.
I chose to be conservative about what dates we clamp, but in theory we
could clamp anything over `2262-04-11 23:47:16.854775807`. But that
would mean actually parsing the date string, which is what pandas is
supposed to do for us, and python stdlib does not have a generic parser
for. And I wasn't sure about the semantics.
=> fix: clamp dates to pandas max

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
The `with_value_from_file` and `which_exist_in_file` functions read files, returning values for use in a study definition. They support case-control studies with variable index dates (#671).
This draft PR adds them to the `patients` module and to the TPP backend. I'd appreciate feedback on all aspects of the implementation, and specifically:
* The testing strategy
* The pros and cons of raising `TypeError`s in `cohortextractor.tpp_backend.patients_with_value_from_file`
* The pros and cons of reading the result of each call into its own temporary table
=> feat: Support case-control studies with variable index dates

cohortextractor/emis_backend.py, tests/test_emis_backend.py
The ONS_DEATHS table has no registration_id, so it can't be joined directly to other tables.  Joins to allow date filtering need to go via the patient table.
Fixes #681 - data extract failed when trying to run the query for this variable:
https://github.com/opensafely/antipsychotics-prescribing-during-COVID-19/blob/2a9ad31cc2f9c290eb697bba64b92c46881940aa/analysis/study_definition.py#L401-L404
With the error:
```PrestoUserError(type=USER_ERROR, name=COLUMN_NOT_FOUND, message="COLUMN_NOT_FOUND: line 9:64: 'o.registration_id'", query_id=20211119_105545_05666_3fci4)
```
The reason for this error is the use of a date in `patients.died_from_any_cause` which is derived from another query.  In this case:
```
antipsychotics_date = patients.with_these_medications(
codelist = …
```
=> fix: Use patient table for date joins on ONS Deaths in EMIS

cohortextractor/date_expressions.py, tests/test_date_expressions.py, tests/test_emis_backend.py, tests/test_tpp_backend.py
=> Add date expressions for first and last day of NHS financial year

cohortextractor/study_definition.py, tests/fixtures/studies/test_patients_from_file/analysis/study_definition_controls.py, tests/fixtures/studies/test_patients_from_file/output/matched_matches.csv, tests/test_smoketest.py
`StudyDefinition.make_df_from_expectations` expects each function in the `patients` module to accept a `return_expectations` argument.
https://github.com/opensafely-core/cohort-extractor/blob/077dbd8819eb5c5f2ca9101dad2c5e1350b0e9d2/cohortextractor/study_definition.py#L294
Previously, `patients.with_value_from_file` and `patients.which_exist_in_file` didn't accept these arguments. However, these functions weren't called from a smoke-test, so @iaindillingham didn't notice that these arguments were missing. Here, we add these arguments and add a smoke-test.
I considered rewriting the above as:
```python
return_expectations = definition_args.get("return_expectations") or {}
```
However, I feel it's safer to make `with_value_from_file` and `which_exist_in_file` consistent with the other …
=> fix: Set expectations for value from/in functions

cohortextractor/emis_backend.py, cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_emis_backend.py, tests/test_tpp_backend.py
Fixes #724 
See issue for rationale for adding this functionality.
Extends `mean_recorded_value` to optionally cover the entire provided range, not just the most recent day of measurement, and adds the equivalent methods for min_recorded_value` and `max_recorded_value`
=> Summary (mean, min, max) recorded values across a range of dates

cohortextractor/study_definition.py, tests/fixtures/studies/test_patients_from_file/analysis/study_definition_controls.py, tests/test_smoketest.py
When we generate dummy data, `with_value_from_file` and `which_exist_in_file` in effect modify the population size from the value given within *project.yaml* to the number of rows in the user-supplied CSV file. However, when a variable in a study definition includes a dependant date, then an `ndarry` of length "population size" is assigned to a data frame of length "number of rows", which raises a `ValueError`.
Here, we add add such a variable to a study definition to recreate the error (thanks for reporting it, @rriefu). We then ensure that when these functions are present in a study definition, the population size is set to the number of rows in the user-supplied CSV file.
---
Pandas indexing gotcha:
```python
df_100 = pandas.DataFrame(data=range(100), columns=["col_a"])
df_200 = …
```
=> fix: Fix population size for dummy data

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
Fixes #696 
From TPP:
> ONS deaths have been updated. There is a new `Place_of_occurrence` column with 6 distinct values:
- Care home
- Elsewhere
- Home
- Hospice
- Hospital
- Other communal establishment
=> Add place_of_death

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_expectation_generators.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
Fixes #713 
Adds the new Therapeutics dataset with a `with_covid_therapeutics` study definition query function, as described in #713 
```
covid_therapeutics = patients.with_covid_therapeutics(
returning = "date",
with_these_statuses = status_codelist,
with_these_therapeutics = therapeutic_codelist,
with_these_indications = indication_codelist,
on_or_after = "index_date",
date_format ="YYYY-MM-DD",
return_first_match_in_period = True,
)
```
Note that there are some duplicate rows for patients, which aer probably not valid, and some "bad" dates that are probably typos (e.g. year 5202).   I'm not excluding or attempting to fix any of these - for now Iwell leave that to the researcher to exclude by setting a sensible date range to filter on, and by creating variables to target specific …
=> Add Therapeutics dataset (Antibody and antivirals)

.github/workflows/build_and_publish.yaml
Fixes #698 
Update checkout action to v2.
=> fix: update checkout action to v2

cohortextractor/patients.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
Fixes #733 
Adds the option to return number_of_episodes, in the same way as `with_these_clinical_events` and `with_these _medications`
=> Return number_of_episodes from with_covid_therapeutics

cohortextractor/pandas_utils.py, requirements.dev.txt, run.sh, tests/test_pandas_utils.py
- fix: driveby fix to make run.sh build the docker image with buildkit
- fix: update pip/pip-tools due to breakage
- fix: clamp all dates to pandas min/max
=> clamp all max dates

Dockerfile
The volume mounts were originally added as metadata, but it turns out if
you don't supply a mount, docker creates one for you with the contents
of that dir in your that lasts beyond the containers lifetime and eats
disk.
=> fix: remove docker volumes

cohortextractor/patients.py, cohortextractor/process_covariate_definitions.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
Fixes #742 
`patients.admitted_to_hospital` already returns `days_in_critical_care`, however this will return the number of days for the first or last matching admission.  
This allows the return options of `total_critical_care_days_in_period` and `total_bed_days_in_period` by summing the days for all admissions during the period.  In the case where there are two or more admissions recorded with the same admission date, we take the max number of days to avoid counting the sames days more than once.
For `total_bed_days_in_period`, the return value required is number of days, but the data recorded is number of nights (sometimes 0, which counts as one bed day).
=> Support returning total bed days and total critical care days from patients.admitted_to_hospital

cohortextractor/emis_backend.py, tests/test_emis_backend.py
This allows a date variable to be passed to `registered_as_of` in the emis backend, e.g. to get all patients registered on the date of death as recorded in ONS (with the caveat that EMIS registrations are limited to just the current/latest registration):
```
study = StudyDefinition(
ons_death_date=patients.died_from_any_cause(
returning="date_of_death", date_format="YYYY-MM-DD"
),
population=patients.registered_as_of("ons_death_date"),
)
```
=> fix: disambiguate column references in emis registered_as_of

cohortextractor/cohortextractor.py
We need some visibility on memory consumption, and something that might
help up point to troublesome measures in a larger run.
=> fix: add some better logging of generate_measures command.

cohortextractor/pandas_utils.py, requirements.prod.txt, tests/test_pandas_utils.py
* bugfix .dta.gz export's were not actually gzip compressed. Upgraded
pandas to enable this.
* used the more recent version 118 dta format, which supports unicode
and longer strings.
* feather compression switched to using zstd as it is both smaller on
disk and equivalent speed to decompress.  Also doesn't require a the
lz4 dependency, so was removed.
* wrote tests to excercise the above exports
=> fix: fix dta exports and feather compression

.pre-commit-config.yaml, requirements.dev.txt, requirements.prod.txt
This bumps black to 22.3.0 to avoid breaking with click 8.1 ([chronicled in this black ticket](https://github.com/psf/black/issues/2964)).
=> bump black to 22.3.0

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
A user wants to match a single code, and provides the argument as a string rather than a list, e.g.
```
rheum_appt_date=patients.outpatient_appointment_date(
returning="date",
find_first_match_in_period=True,
with_these_treatment_function_codes='410',
date_format="YYYY-MM-DD",
between=["index_date - 1 year", "index_date"],
return_expectations={
"incidence": 0.9,
"date": {"earliest": year_preceding, "latest": end_date},
},
)
```
Previously we assumed (but didn't enforce) that the `with_these_treatment_function_codes` argument is either a codelist, or a list of codes that we can convert into a codelist.  Calling `list(codelist)` on a string argument doesn't raise an error, instead it converted the single code into a list of characters - i.e. `["4", "1", "0"]` in the above example, and …
=> fix: convert a single string code to a list

cohortextractor/cohortextractor.py, cohortextractor/emis_backend.py, cohortextractor/log_utils.py, cohortextractor/study_definition.py, cohortextractor/tpp_backend.py, tests/test_logging.py, tests/test_tpp_backend.py
Log some study definition stats and execution timings:
- study definition variable count
- count of variables using codelists
- for each of these, size of the codelist 
- output column count
- table query count
- joins count
- index dates - count, min, max
- measures count
- timing:
- each executed query
- full generate_cohort for each index date, and all index dates
- writing cohort to file
- generate_measures, for each input file
see #777
=> Log some study definition stats and timings

cohortextractor/cohortextractor.py, cohortextractor/emis_backend.py, cohortextractor/log_utils.py, cohortextractor/study_definition.py, cohortextractor/tpp_backend.py, tests/test_logging.py
If there is a range of index dates, the executed SQL is identical for each pass, with the exception of the index date string.  Logging the full SQL each time isn't informative and just inflates the logs.  Instead, log it in full for the first index date, and truncate it to the first line for subsequent index dates, which should still allow us to identify the specific SQL executed when a job failed or was particularly slow, even if we have to look back to the corresponding line for the first index date to find it.
=> fix: Log full SQL on the first index date only

cohortextractor/cohortextractor.py, cohortextractor/mssql_utils.py
fixes #776 
Catches [pymssql errors](https://github.com/pymssql/pymssql/blob/f486f7d79bd2583eba96323cdeca34eb8f14cd2a/src/pymssql/_pymssql.pyx#L117); of the ones listed there, `OperationalError`, `ProgrammingError` and `IntegrityError` seem to be the ones actually raised by pymssql.  
The 2 specific errors from issue #776 are: 
- `Unexpected EOF from the server` (`OperationalError`)
- `Invalid object name 'CodedEvent_SNOMED'` when the snomed table is being built (`ProgrammingError`).  
Other database errors should raise one of these, and I've included `IntegrityError` just in case so that would also get caught as a general database error code.
=> Exit codes for specific database errors

cohortextractor/log_utils.py, tests/test_logging.py
If a timing log is logging a `cursor.execute`, log the actual SQL separately (along with the timing ID) to make the log output a bit clearer
=> fix: Separate SQL loggng out from timing logs

cohortextractor/log_utils.py, cohortextractor/mssql_utils.py, tests/test_logging.py
- Log timing with `time.monotonic`
- Time the batched `fetchall()` calls
=> Improve timing logs

cohortextractor/log_utils.py, cohortextractor/mssql_utils.py, cohortextractor/tpp_backend.py, tests/test_logging.py
Have SQL Server include timings (parse/compile and execute) for each query:
https://docs.microsoft.com/en-us/sql/t-sql/statements/set-statistics-time-transact-sql
Note that I can't find a way to tell what the related query is when logging the timing message.  We have a timing id for all timed queries, and I'm tagging the log with that, but that assumes that the timing message relates to the last SQL query that went through the `cursor.execute` call.  I don't think that will always be the case - if parse/compile happens when `cursor.execute()` is called, but actual execution doesn't happen until results are fetched, then execution timing could be delayed until after other queries have been compiled.  In that case, we'll see duplicate logs for execution time with the same timing id,  and …
=> SQL server stats timing

cohortextractor/cohortextractor.py, cohortextractor/generate_codelist_report.py, tests/test_generate_codelist_report.py
This command does not use study definitions, so we use previously
developed code to embed a default dummy data model for it. This allows
it to be used in local development. Currently, it can only be
run in production.
Note: this work uncovered a bug in the db fixutre cleanup, in that
removing the tables didn't actually work once there was multiple tests
in the module. Rather than figure out the specific deletion order
needed, I just reused the cleanup from the tpp tests.
=> feat: support dummy data for generate_codelist_report command

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
=> Fix: use the mapped db table name in additional supported columns for admitted_to_hospital

cohortextractor/tpp_backend.py, tests/test_emis_backend.py, tests/test_tpp_backend.py
Using a reserved keyword such as "all" as a variable name in a study definition was resulting in a syntax error.  Now we just wrap the variable names in square brackets (the same delimiter that sqlalchemy uses)
=> Fx: Allow reserved keywords to be used as variable names

cohortextractor/study_definition.py, tests/test_expectation_generators.py
Previously the `fixed_value` function wouldn't always work correctly with dummy data generation. It worked OK for the cases we covered in tests, but the behaviour was sensitive to where in the study definition the fixed value appeared.
This PR modifies the test to expose the problem and fixes it by injecting fixed values _after_ we've generated everything else.
=> Fix `fixed_value` in dummy data

cohortextractor/patients.py
This moves the warning from the bottom of the section to the top.
Addresses part of opensafely-core/opensafely-cli#120
=> fix: Add warning to with_gp_consultations docs

cohortextractor/patients.py
Copy missing default and tie-breaking behaviour 
explanation for find_first_match_in_period and 
find_last_match_in_period args from 
with_these_clinical_events to
with_these_medications
=> Add defaults to with_these_medications docstring

cohortextractor/patients.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
=> feat: Add with_at_least_one_day_in_critical_care filter to admitted_to_hospital

cohortextractor/emis_backend.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
These were getting introduced via the `patients.with_value_from_file()`
function when loading data saved using Pandas which encodes missing
values as `NaN`. This resulted in SQL like this:
INSERT INTO #tmp4_vax_date_covid_1_file (patient_id, vax_date_covid_1) VALUES
(123456, '20210101'),
(123457, nan);
Which of course leads to the error:
Invalid column name 'nan'
=> fix: Fix handling of NaN values

cohortextractor/tpp_backend.py, tests/test_tpp_backend.py
If you try to return the matching category from a codelist using a date
drawn from another query which itself also returns a cateogry then you
get the error:
Ambiguous column name 'category'
Example of a problematic query here:
https://github.com/opensafely/amr-uom-brit/blob/4c0879664ca/analysis/study_definition_ab_type_OS_new_2021.py#L110-L134
=> fix: Fix ambiguous column name

cohortextractor/__init__.py, cohortextractor/cohortextractor.py, cohortextractor/exceptions.py, tests/fixtures/studies/test_params/analysis/study_definition.py, tests/test_cohortextractor.py, tests/test_smoketest.py
This teaches `generate_cohort` to accept a new, multi-valued `--param` argument e.g.
cohortextractor generate_cohort --param key1=value1 --param key2=value2 --param key3
The study definition can access these via the `params` dict in the `cohortextractor` module:
```py
from cohortextractor import params
print(params)
```
There was a suggestion earlier of using `--arg` for this, but I think `--param` avoids confusion with other kinds of thing which are also called "arguments", and fits neatly with the term "parameterised study definition".
This was all much harder than it ought to be because implicit in this feature is the need for the output file name to be customised. Previously the output directory and format could be changed, but the file name was determined by the study definition name …
=> Support parameterising study definitions

cohortextractor/cohortextractor.py, tests/test_cohortextractor.py
The latter is redundant, but job-runner insists on adding it to the `run` command in any case so we can't just reject it outright. Instead we now check that it agrees with the directory in `--output-file` and only throw an error if they're different.
For consistency we do the same with `--output-format` although job-runner doesn't inject that for us.
=> fix: Allow both `--output-file` and `--output-dir` to be set

cohortextractor/cohortextractor.py, cohortextractor/emis_backend.py, cohortextractor/flags.py, cohortextractor/tpp_backend.py, tests/test_cohortextractor.py, tests/test_emis_backend.py, tests/test_tpp_backend.py
The deleted comment talks about adding a --without-fix flag, but I think that introduces unnecessary complexity and we can add it later if we need to.
=> fix: Always enable date range fix

cohortextractor/cohortextractor.py
We've known about this type of error for ages (see [issue][1]) but when we first wrote this error handling code (#791) we hadn't seen it in a while so we decided to exclude it and see if it reoccurs. It has reoccurred; not terribly often but enough times that it's worth handling it here.
Note that transient errors which occur when downloading results are automatically handled by the retry code so we never see them. This error handling concerns errors which occur before we've finished generating the results.
[1]: https://github.com/opensafely-core/cohort-extractor/issues/776#issuecomment-1091675829
=> fix: Handle another type of transient database error

cohortextractor/patients.py
The text hasn't changed; it's simply indented by four spaces such that MkDocs formats it as a callout. This avoids [an empty warning callout](https://docs.opensafely.org/study-def-variables/#cohortextractor.patients.with_gp_consultations).
=> Fix warning callout

pyproject.toml
By default (according to --help as of v22.8.0) black is already ignoring this list of directories:
/(\.direnv|\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|venv|\.svn|_build|buck-out|build|dist|__pypackages__)/
By using --extend-exclude we can layer on top of that.
Refs: opensafely-core/repo-template#85
=> Use --extend-exclude and remove existing excludes

cohortextractor/date_expressions.py
For $REASONS, when generating the SQL expression to access a date column, cohortextractor wraps the column in a function to format it as a string. If we want to then do date arithmetic on this value we have to parse it back to a date. To try to mitigate this terribleness a bit we try to spot cases where we're formatting a date as a string only to immediately parse it again and then rewrite the expression to shortcut this process. We identify these patterns using a regex.
In #875 we started quoting all column names to avoid issues where SQL keywords were used as names (prior to the `with_value_from_file()` code, column names had never been user-definable to this hadn't been a problem).
However the addition of the `[` and `]` characters to the column names broke the regex designed to spot …
=> fix: Fix regex identifying shortcut-able date expressions

cohortextractor/patients.py
Changes are based on discussion with Christ Bates from TPP, following a chane in understanding of the underlying data being used by the `patients.with_gp_consultations` function (`Appointment` rather than `Consultation`).
Whereas entries in the `Consultation` table are created on just about every interaction with the patient record, `Appointment` records are only made when a specific appointment is made. This means that appointments are likely the most reliable indication of GP activity available in the TPP data.
=> revise appointment-consultation docs warnings

Dockerfile, Makefile, docker-compose.yml
This was an oversight, or somehow got removed.
This allows us to tag telemetry about jobs with the specific
cohortextractor version it was run with.
=> fix: add version and build timestamps labesl to docker image.

cohortextractor/tpp_backend.py, tests/tpp_backend_setup.py
For reasons I don't understand, the ONS CIS data is now in a table called ONS_CIS_New.
=> feat: Update name of ONS_CIS table

cohortextractor/cohortextractor.py
`generate_measures` has grown a `--param` parameter.
```
$ cohortextractor generate_measures --help
usage: cohortextractor generate_measures [-h] [--output-dir OUTPUT_DIR] [--study-definition {all}] [--skip-existing] [--param PARAMS [PARAMS ...]]
optional arguments:
-h, --help            show this help message and exit
--output-dir OUTPUT_DIR
Location to store output files
--study-definition {all}
Study definition file containing measure definitions to use
--skip-existing       Do not regenerate measure if output file already exists
--param PARAMS [PARAMS ...]
Additional parameter to pass to study definition
```
=> feat: Allow custom params for generate_measures

cohortextractor/ons_cis_utils.py, cohortextractor/study_definition.py, cohortextractor/tpp_backend.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
`ONS_CIS.visit_id` has become `ONS_CIS_New.pseudo_visit_id`, and has switched from a `varchar` to a `varbinary`. We use this column to break ties, and don't reveal it to the user, so we simply switch names and types.
=> fix: Switch ONS CIS `visit_id` to `pseudo_visit_id`

cohortextractor/tpp_backend.py
Avoiding this in the general case would be fiddly, so I've made the smallest possible change here.
See https://bennettoxford.slack.com/archives/C33TWNQ1J/p1677690662258539
=> fix: Qualify column name to avoid clash with user-supplied table

cohortextractor/patients.py
In examples that don't discuss different date formats, we now use "YYYY-MM-DD", as "YYYY-MM" is a source of confusion.
=> docs: Update date format in examples

cohortextractor/cohortextractor.py, cohortextractor/custom_medication_dictionary.csv, cohortextractor/update_custom_medication_dictionary.py, tests/test_update_custom_medication_dictionary.py
This sub-command updates the `CustomMedicationDictionary` table. (In reality, it first drops and then creates it, but it's called "update" for consistency with `update_vmp_mapping`.) This table is required by opensafely-core/ehrql#1270. Whilst its maintenance should, arguably, be handled by a separate tool, we already drop and create tables in the temporary database in cohort-extractor, so the maintenance of this table is here for consistency.
The implementation follows that of `cohortextractor.update_vmp_mapping` closely. I've added a couple of QOL improvements to the test and, to preserve my sanity, avoided using `unittest.mock`.
=> Add `update_custom_medication_dictionary`

cohortextractor/tpp_backend.py
Uses the same approach described in:
* https://github.com/opensafely-core/ehrql/pull/1400
Closes #965
=> Avoid locking sys.table when creating temporary tables

cohortextractor/tpp_backend.py
We removed these as part of #968. However pymssql defaults to holding an open transaction which defeats the point of the lock avoidance behaviour we implemented so we now make sure to explicitly commit after each step.
Theoretically we could just put the connection into autocommit mode, but we want to do the smallest possible change here while we observe the effect.
=> fix: Explicitly commit after creating temporary tables

.github/workflows/build_and_publish.yaml
According to the Github docs, a "permissive" Github token (which is what we have) has "package: write" permissions by default: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
And also according the Github docs, if you explicitly specify _any_ permission in the workflow flow then all permissions you haven't specified revert to `none`:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defining-access-for-the-github_token-scopes
This means that explictly including `package: write` as we were doing is not only unnecessary but prevents us having permission to push version tags, meaning that the `tag-new-version` action failed with:
Error: Resource not accessible by integration
Obviously …
=> fix: Fix workflow permissions

cohortextractor/tpp_backend.py, tests/test_logging.py, tests/test_tpp_backend.py
The previous default was a temporary measure to facilitate deployment.
=> fix: Set default T1OO config to false

README.md
It is not immediately obvious to someone encountering this repository
outside of the context of OpenSAFELY (for example, reading the
documentation) that active development is on ehrQL, which replaces
cohort-extractor for new OpenSAFELY studies.
=> docs: Document that ehrQL follows cohort-extractor

cohortextractor/tpp_backend.py, tests/test_logging.py, tests/test_tpp_backend.py, tests/tpp_backend_setup.py
This switches the T1OO logic to use a table of explicitly _allowed_ patients, rather than a table of exclusions. This allows TPP to apply more complex criteria in determining the appropriate set of patients.
=> Switch to inclusion table for T1OO handling

.github/workflows/test_runner.yaml, Makefile
Docker Compose v1 is deprecated and has been removed from Github Actions Runner images:
https://github.blog/changelog/2024-04-10-github-hosted-runner-images-deprecation-notice-docker-compose-v1/ https://docs.docker.com/compose/migrate/
Note that I've only changed the invocations used in Github Actions because that's what I need to run in order to build a new image. It looks like we also use docker-compose locally. Probably that version will need updating and the various invocations fixing, but I don't have time for this right now.
=> Update to Docker Compose v2 syntax
